accounts/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    # password change
    path('password_change/', views.LogoutView.as_view(), name='password_change'),
    path('password_change_done/', views.LogoutView.as_view(), name='password_change_done'),
    # password reset
    path('reset_password/', views.PasswordResetView.as_view(), name='reset_password'),
    path('password_reset_done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

api/urls.py
from django.urls import path

app_name = "api"

urlpatterns = []

app/branches/urls.py
from django.urls import path
from . import views

app_name = "branches"

urlpatterns = [
    path("<int:bpk>", views.BranchesView.as_view(), name="landing"),
    path("<int:bpk>/products", views.ProductsView.as_view(), name="products"),
    path("<int:bpk>/products/<int:pk>", views.ProductDetailView.as_view(), name="product-detail"),
    path("<int:bpk>/sales", views.SalesView.as_view(), name="sales"),
    path("<int:bpk>/sales/form", views.SalesFormView.as_view(), name="sales_form"),
    path("<int:bpk>/sales/form/<int:pk>", views.SalesFormView.as_view(), name="sales_form_update"),
    path("<int:bpk>/sales/analytics", views.SalesAnalyticsView.as_view(), name="sales_analytics"),
]

app/company/urls.py
from django.urls import path
from . import views

app_name = "company"

urlpatterns = [
    path("", views.LandingPageView.as_view(), name="landing"),
    path("branches/", views.BranchesPageView.as_view(), name="branches"),
    path("users/", views.UsersListView.as_view(), name="users"),
    path("products/", views.ProductListView.as_view(), name="products"),
]

dotsales/urls.py
from django.contrib import admin
from django.urls import path, include

from api.api import global_api

from .appsConfig import getAppUrls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", global_api.urls),

    path("unicorn/", include("django_unicorn.urls")),
]

urlpatterns += getAppUrls()

dotsales/templates/cotton/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Tereka Online - {{ title }}</title>
		<link rel="preconnect" href="https://fonts.googleapis.com" />
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
		<link
			href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,200..800;1,200..800&display=swap"
			rel="stylesheet" />

		<link href="https://cdn.jsdelivr.net/npm/daisyui@5" rel="stylesheet" type="text/css" />
		<script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>

		<script
			src="https://cdn.jsdelivr.net/npm/htmx.org@2.0.7/dist/htmx.min.js"
			integrity="sha384-ZBXiYtYQ6hJ2Y0ZNoYuI+Nq5MqWBr+chMrS/RkXpNzQCApHEhOt2aY8EJgqwHLkJ"
			crossorigin="anonymous"></script>

		<script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>

		<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0&icon_names=edit" />

        <link href='https://cdn.boxicons.com/fonts/basic/boxicons.min.css' rel='stylesheet'>

		<style>
			@plugin "daisyui" {
				themes: light --default;
			}
			@plugin "daisyui/theme" {
				name: "light";
				default: true;

				/* border radius */
				--radius-selector: 1rem;
				--radius-field: 2rem;
				--radius-box: 2rem;

				/* base sizes */
				--size-selector: 0.5rem;
				--size-field: 0.5rem;

				/* border size */
				--border: 1px;

				/* effects */
				--depth: 0;
				--noise: 0;
			}
			body {
				font-family: "Plus Jakarta Sans", sans-serif;
			}
            .hamburger-btn {
                position: fixed;
                bottom: 2rem;
                right: 2rem;
                overflow: hidden;
                border-radius: .25rem;
                border-color: var(--color-primary-content);
                border-style: solid;
                border-width: 1px;

                background-color: var(--color-primary);

                svg {
                    stroke: var(--color-primary-content);
                    stroke-width: 10;
                    stroke-linecap: round;
                    stroke-linejoin: round;
                    transition: translate .5s, rotate .5s;
                }

                .line {
                    stroke-dasharray: 60 31 60 300;
                    transition: .5s;
                }

                &[aria-expanded="true"] .hamburger {
                    translate: 2px -3px;
                    rotate: .125turn;
                }

                &[aria-expanded="true"] .line {
                    stroke-dasharray: 60 105 60 300;
                    stroke-dashoffset: -90;
                }
            }
		</style>
	</head>
	<body
		class="h-screen bg-white overflow-y-auto"
		hx-headers='{"x-csrftoken": "{{ csrf_token }}"}'>
		{{ slot }} {% block content %}{% endblock %}
        {% if error_message %}
        <script>
            console.log(`{{ error_message|safe }}`)
        </script>
        {% endif %}
	</body>
</html>

dotsales/templates/cotton/layout.html
{% load static mytags %}

<c-base title="{{ title }}">
	<div
		class="h-screen w-full bg-base-100"
		x-data="{
            pdf_loading: false,
            global_loading: false,
            error: '',
            show_sidebar: true,
            sm_show: false,
            async handlePDF() {
                this.pdf_loading = true;
                this.error = '';

                const result = await window.generatePDF();

                this.pdf_loading = false;

                if (result !== 0) {
                    this.error = result;
                    setTimeout(() => this.error = '', 5000);
                }
            },
            init(){
                document.querySelectorAll('.link-group').forEach((el) => {
                    if (el.querySelectorAll('li').length === 0) {
                        el.remove();
                    }
                })
            }
        }">
		<div class="">
			<div
				x-cloak
				x-show="pdf_loading"
				class="fixed inset-0 grid place-content-center text-center gap-2 text-primary bg-base-100/70">
				<span class="loading loading-infinity loading-xl"></span>
				{% comment %} <span class="loading loading-bars loading-md"></span> {% endcomment %}
				<p class="text-sm font-medium">Generating your PDF...</p>
			</div>
			<div
				x-cloak
				x-show="global_loading"
				class="fixed inset-0 grid place-content-center text-center gap-2 text-primary bg-base-100/70 z-50">
				<span class="loading loading-infinity loading-xl"></span>
			</div>

			<div
				id="full-htmx-loader"
				class="htmx-indicator fixed inset-0 grid place-content-center text-center gap-2 text-primary bg-base-100/70 z-full">
				<span class="loading loading-infinity loading-xl scale-200"></span>
			</div>

			<div
				x-cloak
				x-show="error"
				x-transition
				class="alert alert-error mt-4 fixed top-8 right-8">
				<span x-text="error"></span>
			</div>
		</div>
        <div class="flex h-screen w-full">
            <div class="h-screen grid fixed top-0 z-10 transition-all bg-base-content/30 md:bg-transparent md:static" :class="{ 'md:hidden': !show_sidebar, 'left-0 right-0': sm_show, 'left-[-100%]': !sm_show }">
                <div class="h-screen w-64 flex flex-col bg-base-100">
                    <!-- Header -->
                    <div class="p-4 w-full">
                        <div class="flex items-center gap-2">
                            <div
                                class="aspect-square w-8 rounded-sm bg-primary grid place-content-center font-semibold text-primary-content">
                                C
                            </div>
                            <div>
                                <h2>{{ company.name }}</h2>
                            </div>
                        </div>
                    </div>
    
                    <!-- Scrollable Content -->
                    <div class="flex-1 overflow-y-auto py-2 space-y-4">
                        <div class="link-group">
                            <h2 class="text-xs font-medium opacity-60 uppercase px-4">Landing</h2>
                            <ul class="menu w-full">
                                <li><a href="{% url 'company:branches' %}">Branches</a></li>
                            </ul>
                        </div>
                        <div class="link-group">
                            <h2 class="text-xs font-medium opacity-60 uppercase px-4">
                                Accounts Management
                            </h2>
                            <ul class="menu w-full">
                                {% if request.user|has_perm:"users.view_user" %}
                                <li><a href="{% url 'company:users' %}">Users</a></li>
                                {% endif %}
                            </ul>
                        </div>
                        
                        <div class="link-group">
                            <h2 class="text-xs font-medium opacity-60 uppercase px-4">Inventory</h2>
                            <ul class="menu w-full">
                                {% if request.user|has_perm:"products.view_product" %}
                                <li><a href="{% url 'company:products' %}">Products</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
    
                    <!-- Footer -->
                    <div class="p-4 border-t border-base-300 text-sm text-base-content">
                        <div class="grid relative">
                            <div class="dropdown dropdown-top w-full">
                                <button
                                    class="w-full bg-base-200 hover:bg-base-300 p-4 rounded-box transition-all cursor-pointer">
                                    <div class="grid grid-flow-col items-center space-x-2">
                                        <div class="avatar avatar-placeholder">
                                            <div
                                                class="bg-secondary text-secondary-content w-8 rounded-full grid place-content-center">
                                                <span class="text-xs"
                                                    >{{ request.user.profile.get_initials }}</span
                                                >
                                            </div>
                                        </div>
    
                                        <div class="grid text-left overflow-hidden">
                                            <h2 class="font-semibold text-xs">
                                                {{ request.user.profile.get_full_name }}
                                            </h2>
                                            <p class="text-xs opacity-60">
                                                {{ request.user.email }}
                                            </p>
                                        </div>
                                    </div>
                                </button>
    
                                <div
                                    tabindex="0"
                                    aria-label="Account options"
                                    class="dropdown-content min-w-40 rounded-box bg-base-100 text-base-content shadow-sm">
                                    <div class="p-4">
                                        <div class="grid place-content-center text-center mb-4">
                                            <p class="text-sm opacity-60">Confirm below to logout.</p>
                                        </div>
                                        <form action="{% url 'users:logout' %}" method="post">
                                            {% csrf_token %}
                                            <button class="btn btn-soft btn-error w-full">
                                                Logout
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <button @click="sm_show = !sm_show;console.log(sm_show)" title="Menu button" class="hamburger-btn grid grid-flow-col cursor-pointer md:hidden z-20"
                :aria-expanded="sm_show ? true : false">
                <svg class="hamburger w-10" fill="none" viewbox="-10 -10 120 120">
                    <path class="line" d="m 20 40 h 60 a 1 1 0 0 1 0 20 h -60 a 1 1 0 0 1 0 -40 h 30 v 70"></path>
                </svg>
                <div class="text-primary-content h-full grid content-center pr-2 text-sm">
                    <span>Menu</span>
                </div>
            </button>
    
            <div class="flex-1 flex flex-col p-1 relative grid" id="app-slot">
                {% comment %} <button
                    type="button"
                    class="btn btn-square btn-sm text-lg btn-ghost absolute bottom-1 left-1 opacity-70"
                    @click="show_sidebar = !show_sidebar"
                    :title="show_sidebar ? 'Close sidebar' : 'Open sidebar'">
                    <span class="icon-panel-left-close" x-show="show_sidebar" x-cloak></span>
                    <span class="icon-panel-left-open" x-show="!show_sidebar" x-cloak></span>
                </button> {% endcomment %}
                <div
                    class="rounded-box bg-gradient-to-br from-[#F0F4F8] to-[#d6dadd] h-full w-full overflow-y-auto p-1 sm:p-2 md:p-4 pb-28 md:pb-4">
                    {{ slot }}
                </div>
            </div>
        </div>
	</div>
</c-base>

dotsales/templates/cotton/layout2.html
{% load static mytags %}

<c-base title="{{ title }}">
	<div
		class="flex h-screen bg-base-100"
		x-data="{
            pdf_loading: false,
            global_loading: false,
            error: '',
            show_sidebar: true,
            sm_show: false,
            async handlePDF() {
                this.pdf_loading = true;
                this.error = '';

                const result = await window.generatePDF();

                this.pdf_loading = false;

                if (result !== 0) {
                    this.error = result;
                    setTimeout(() => this.error = '', 5000);
                }
            },
            init(){
                document.querySelectorAll('.link-group').forEach((el) => {
                    if (el.querySelectorAll('li').length === 0) {
                        el.remove();
                    }
                })
            }
        }">
		<div class="">
			<div
				x-cloak
				x-show="global_loading"
				class="fixed inset-0 grid place-content-center text-center gap-2 text-primary bg-base-100/70 z-50">
				<span class="loading loading-infinity loading-xl"></span>
			</div>

			<div
				id="full-htmx-loader"
				class="htmx-indicator fixed inset-0 grid place-content-center text-center gap-2 text-primary bg-base-100/70 z-full">
				<span class="loading loading-infinity loading-xl scale-200"></span>
			</div>

			<div
				x-cloak
				x-show="error"
				x-transition
				class="alert alert-error mt-4 fixed top-8 right-8">
				<span x-text="error"></span>
			</div>
		</div>
        <div class="flex h-screen w-full">
            <div class="h-screen grid fixed top-0 z-10 transition-all bg-base-content/30 md:bg-transparent md:static" :class="{ 'md:hidden': !show_sidebar, 'left-0 right-0': sm_show, 'left-[-100%]': !sm_show }">
                <div class="h-screen w-64 flex flex-col bg-base-100">
                    <!-- Header -->
                    <div class="p-4 w-full">
                        <div class="flex items-center gap-2">
                            <div
                                class="aspect-square w-8 rounded-box bg-neutral grid place-content-center font-semibold text-neutral-content">
                                B
                            </div>
                            <div class="text-xs">
                                <a {% if user.profile.admin_access %}href="{% url 'company:branches' %}" class="link"{% endif %}>
                                    <h2>{{ company.name }}</h2>
                                </a>
                                <p class="font-semibold">{{ branch.name }}</p>
                            </div>
                        </div>
                    </div>
    
                    <!-- Scrollable Content -->
                    <div class="flex-1 overflow-y-auto py-2 space-y-4">
                        <div class="link-group">
                            {% comment %} <h2 class="text-xs font-medium opacity-60 uppercase px-4">Landing</h2> {% endcomment %}
                            <ul class="menu w-full">
                                <li><a href="{% url 'branches:landing' branch.id %}">Landing</a></li>
                            </ul>
                        </div>
                        <div class="link-group">
                            <h2 class="text-xs font-medium opacity-60 uppercase px-4">
                                Inventory
                            </h2>
                            <ul class="menu w-full">
                                {% if request.user|has_perm:"products.view_branchproduct" %}
                                <li><a href="{% url 'branches:products' branch.id %}">Products</a></li>
                                {% endif %}
                            </ul>
                        </div>
                        <div class="link-group">
                            <h2 class="text-xs font-medium opacity-60 uppercase px-4">
                                Sales
                            </h2>
                            <ul class="menu w-full">
                                {% if request.user|has_perm:"sales.view_sale" %}
                                <li><a href="{% url 'branches:sales' branch.id %}">Landing</a></li>
                                {% endif %}
                                {% if request.user|has_perm:"sales.add_sale" %}
                                <li><a href="{% url 'branches:sales_form' branch.id %}">POS</a></li>
                                {% endif %}
                                {% if request.user|has_perm:"sales.analyze_profit" %}
                                <li><a href="{% url 'branches:sales_analytics' branch.id %}">Analytics</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
    
                    <!-- Footer -->
                    <div class="p-4 border-t border-base-300 text-sm text-base-content">
                        <div class="grid relative">
                            <div class="dropdown dropdown-top w-full">
                                <button
                                    class="w-full bg-base-200 hover:bg-base-300 p-4 rounded-box transition-all cursor-pointer">
                                    <div class="grid grid-flow-col items-center space-x-2">
                                        <div class="avatar avatar-placeholder">
                                            <div
                                                class="bg-secondary text-secondary-content w-8 rounded-full grid place-content-center">
                                                <span class="text-xs"
                                                    >{{ request.user.profile.get_initials }}</span
                                                >
                                            </div>
                                        </div>
    
                                        <div class="grid text-left overflow-hidden">
                                            <h2 class="font-semibold text-xs">
                                                {{ request.user.profile.get_full_name }}
                                            </h2>
                                            <p class="text-xs opacity-60">
                                                {{ request.user.email }}
                                            </p>
                                        </div>
                                    </div>
                                </button>
    
                                <div
                                    tabindex="0"
                                    aria-label="Account options"
                                    class="dropdown-content min-w-40 rounded-box bg-base-100 text-base-content shadow-sm">
                                    <div class="p-4">
                                        <div class="grid place-content-center text-center mb-4">
                                            <p class="text-sm opacity-60">Confirm below to logout.</p>
                                        </div>
                                        <form action="{% url 'users:logout' %}" method="post">
                                            {% csrf_token %}
                                            <button class="btn btn-soft btn-error w-full">
                                                Logout
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <button @click="sm_show = !sm_show;console.log(sm_show)" title="Menu button" class="hamburger-btn grid grid-flow-col cursor-pointer md:hidden z-20"
                :aria-expanded="sm_show ? true : false">
                <svg class="hamburger w-10" fill="none" viewbox="-10 -10 120 120">
                    <path class="line" d="m 20 40 h 60 a 1 1 0 0 1 0 20 h -60 a 1 1 0 0 1 0 -40 h 30 v 70"></path>
                </svg>
                <div class="text-primary-content h-full grid content-center pr-2 text-sm">
                    <span>Menu</span>
                </div>
            </button>
    
            <div class="flex-1 flex flex-col p-1 relative grid" id="app-slot">
                {% comment %} <button
                    type="button"
                    class="btn btn-square btn-sm text-lg btn-ghost absolute bottom-1 left-1 opacity-70"
                    @click="show_sidebar = !show_sidebar"
                    :title="show_sidebar ? 'Close sidebar' : 'Open sidebar'">
                    <span class="icon-panel-left-close" x-show="show_sidebar" x-cloak></span>
                    <span class="icon-panel-left-open" x-show="!show_sidebar" x-cloak></span>
                </button> {% endcomment %}
                <div
                    class="rounded-box bg-gradient-to-br from-[#F0F4F8] to-[#d6dadd] h-full w-full overflow-y-auto p-1 sm:p-2 md:p-4 pb-28 md:pb-4">
                    {{ slot }}
                </div>
            </div>
        </div>
	</div>
</c-base>

dotsales/templates/cotton/loader.html
<div class="fixed inset-0 z-50 grid place-content-center bg-base-100/80" {{ attrs }}>
    <span class="loading loading-infinity loading-xl"></span>
</div>