accounts/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    # password change
    path('password_change/', views.LogoutView.as_view(), name='password_change'),
    path('password_change_done/', views.LogoutView.as_view(), name='password_change_done'),
    # password reset
    path('reset_password/', views.PasswordResetView.as_view(), name='reset_password'),
    path('password_reset_done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

api/urls.py
from django.urls import path

app_name = "api"

urlpatterns = []

app/branches/urls.py
from django.urls import path
from . import views

app_name = "branches"

urlpatterns = [
    path("<int:bpk>", views.BranchesView.as_view(), name="landing"),
    path("<int:bpk>/products", views.ProductsView.as_view(), name="products"),
    path("<int:bpk>/products/<int:pk>", views.ProductDetailView.as_view(), name="product-detail"),
    path("<int:bpk>/sales", views.SalesView.as_view(), name="sales"),
    path("<int:bpk>/sales/form", views.SalesFormView.as_view(), name="sales_form"),
    path("<int:bpk>/sales/form/<int:pk>", views.SalesFormView.as_view(), name="sales_form_update"),
    path("<int:bpk>/sales/analytics", views.SalesAnalyticsView.as_view(), name="sales_analytics"),
]

app/company/urls.py
from django.urls import path
from . import views

app_name = "company"

urlpatterns = [
    path("", views.LandingPageView.as_view(), name="landing"),
    path("branches/", views.BranchesPageView.as_view(), name="branches"),
    path("users/", views.UsersListView.as_view(), name="users"),
    path("products/", views.ProductListView.as_view(), name="products"),
]

dotsales/urls.py
from django.contrib import admin
from django.urls import path, include

from api.api import global_api

from .appsConfig import getAppUrls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", global_api.urls),

    path("unicorn/", include("django_unicorn.urls")),
]

urlpatterns += getAppUrls()

accounts/companies/models/Branch.py
from django.db import models
from django.utils.translation import gettext_lazy as _

class Branch(models.Model):
    company = models.ForeignKey("companies.Company", on_delete=models.CASCADE, related_name="branches")
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=200, blank=True, null=True)

    email = models.EmailField(blank=True, null=True)
    phone_1 = models.CharField(_("Phone 1"), max_length=15, blank=True, null=True)
    phone_2 = models.CharField(_("Phone 2"), max_length=15, blank=True, null=True)

    class Meta:
        unique_together = ("company", "name")

    def __str__(self):
        return f"{self.company.name} - {self.name}"
    
    def verify_product(self, product):
        return self.branch_products.filter(product=product).exists()

accounts/companies/models/Company.py
from django.db import models

class Company(models.Model):
    name = models.CharField(max_length=150, unique=True)
    contact = models.CharField(max_length=50, blank=True, null=True)
    address = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

inventory/products/models/BranchProduct.py
from django.db import models

class BranchProduct(models.Model):
    branch = models.ForeignKey("companies.Branch", on_delete=models.CASCADE, related_name="branch_products")
    product = models.ForeignKey("products.Product", on_delete=models.CASCADE, related_name="branch_products")
    is_active = models.BooleanField(default=True)
    stock = models.DecimalField(max_digits=10, decimal_places=2, default=0)


    class Meta:
        unique_together = ("branch", "product")

    def __str__(self):
        return f"{self.product.name} at {self.branch.name}"
    
    def get_stock(self):
        # return stock omitting irrelevant decimal points ie .00
        return self.stock.normalize()
    
    def get_worth(self):
        return int(self.get_stock() * self.product.unit_price)

accounts/companies/forms.py
from django import forms
from accounts.users.models import User, UserProfile
from django.contrib.auth.hashers import make_password

class CompanyAdminUserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, required=True)

    # Profile fields
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    middle_name = forms.CharField(required=False)
    gender = forms.ChoiceField(choices=UserProfile._meta.get_field("gender").choices, required=False)
    phone_1 = forms.CharField(required=False)
    phone_2 = forms.CharField(required=False)

    class Meta:
        model = User
        fields = ["email", "username", "password"]

    def save(self, commit=True, company=None):
        user = super().save(commit=False)
        user.password = make_password(self.cleaned_data["password"])
        user.username = self.cleaned_data["email"]
        user.company = company
        user.is_company_admin = True
        if commit:
            user.save()
            UserProfile.objects.create(
                user=user,
                first_name=self.cleaned_data["first_name"],
                last_name=self.cleaned_data["last_name"],
                middle_name=self.cleaned_data.get("middle_name"),
                gender=self.cleaned_data.get("gender"),
                phone_1=self.cleaned_data.get("phone_1"),
                phone_2=self.cleaned_data.get("phone_2"),
            )
        return user

accounts/users/forms.py
from django.contrib.auth.forms import PasswordResetForm
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.conf import settings

class CustomPasswordResetForm(PasswordResetForm):
    def save(self, request=None, custom_message=None, domain="app.terekaonline.com", reset_type="reset", **kwargs):
        protocol = "http"
        if settings.DEBUG:
            domain = "localhost:8000"
            protocol = "http"
        if request:
            domain = get_current_site(request).domain
            if request.is_secure():
                protocol = "https"
            
        email = self.cleaned_data["email"]
        for user in self.get_users(email):
            context = {
                'email': user.email,
                'domain': domain,
                'site_name': 'Tereka Online',
                'uid': urlsafe_base64_encode(force_bytes(str(user.pk))),
                'user': user,
                'token': default_token_generator.make_token(user),
                'protocol': protocol,
                'custom_message': custom_message,  # 👈 my custom context
                'reset_type': "reset"
            }

            subject = "Account Activation"
            body = render_to_string('registration/password_reset_email_message.html', context)
            html_email = render_to_string('registration/password_reset_email.html', context)

            email_message = EmailMultiAlternatives(subject, body, kwargs.get('from_email'), [user.email])
            email_message.attach_alternative(html_email, "text/html")
            email_message.send()

accounts/users/views.py
from django.shortcuts import render
from django.conf import settings
from django.contrib.auth import authenticate, login, get_user_model, logout
from django.urls import reverse, reverse_lazy
from django.shortcuts import redirect
from django.views import View
from django.contrib.auth import views

from .forms import CustomPasswordResetForm


User = get_user_model()

# Create your views here.
class LoginView(View):
    def get(self, request):
        return render(request, 'registration/login.html', {})
    def post(self, request):
        data = request.POST
        get_data = request.GET
        email = data.get('email').strip()
        password = data.get('password')
        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            next_route = get_data.get('next')
            if next_route:
                return redirect(next_route)
            return redirect(settings.LOGIN_REDIRECT_URL)
        
        user_obj = User.objects.filter(email=email).exists()
        email_error = "Email does not exist."
        password_error = None

        if user_obj:
            email_error = None
            password_error = "Password is incorrect."

        context = {
            "email": email,
            "password": password,
            "email_error": email_error,
            "password_error": password_error,
        }
        return render(request, 'registration/login.html', context)

class LogoutView(View):
    def post(self, request):
        logout(request)
        return redirect(settings.LOGOUT_REDIRECT_URL)

class PasswordResetView(views.PasswordResetView):
    form_class = CustomPasswordResetForm
    success_url = reverse_lazy("users:password_reset_done")
    html_email_template_name = 'registration/password_reset_email.html'

    def form_valid(self, form):
        # Inject custom context into the email
        return form.save(
            request=self.request,
            from_email=settings.DEFAULT_FROM_EMAIL,
            custom_message='Welcome to Tereka Online! Click below to reset your password.',
        ) or super().form_valid(form)

class PasswordResetDoneView(views.PasswordResetDoneView):
    pass

class PasswordResetConfirmView(views.PasswordResetConfirmView):
    success_url = reverse_lazy("users:password_reset_complete")

class PasswordResetCompleteView(views.PasswordResetCompleteView):
    pass

class PasswordChangeView(views.PasswordChangeView):
    success_url = reverse_lazy("users:password_change_done")

class PasswordChangeDoneView(views.PasswordChangeDoneView):
    pass

app/company/views.py
from django.db import transaction
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import View

from accounts.c_auth.mixins import AdminAccessRequiredMixin
from accounts.c_auth.mixins import AdminAccessRequiredMixin
from accounts.c_auth.models import CGroup
from accounts.companies.models import Branch
from accounts.users.models import UserProfile
# Create your views here.
class BranchesPageView(LoginRequiredMixin, AdminAccessRequiredMixin, View):
    def get(self, request):
        return render(request, 'company/branches.html', {})
    
    def post(self, request, *args, **kwargs):
        data = request.POST
        user = request.user
        if not user.is_company_admin:
            return self.get(request, *args, **kwargs)
        
        company = user.company

        pk = data.get("pk", None)
        name = data.get("branch_name")
        location = data.get("location")
        email = data.get("email")
        phone_1 = data.get("phone_1")
        phone_2 = data.get("phone_2")

        with transaction.atomic():
            if pk:
                branch = company.branches.get(pk=pk)
                branch.name = name
                branch.location = location
                branch.email = email
                branch.phone_1 = phone_1
                branch.phone_2 = phone_2
                branch.save()
            else:
                company.branches.create(
                    company=company,
                    name=name,
                    email=email,
                    phone_1=phone_1,
                    phone_2=phone_2,
                    location=location
                )

        return self.get(request, *args, **kwargs)


class LandingPageView(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        if user.is_company_admin or user.profile.admin_access:
            return redirect(reverse_lazy("company:branches"))
        return render(request, 'company/landing.html', {})


class UsersListView(LoginRequiredMixin, AdminAccessRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        user = request.user
        company = user.company

        users = company.users.all().prefetch_related("profile")
        error_message = kwargs.get("error_message", None)
        roles = CGroup.objects.all()

        context = {
            "users": users,
            "error_message": error_message,
            "roles": roles
        }
        
        return render(request, 'company/users.html', context)
    

    def post(self, request, *args, **kwargs):
        user = request.user
        company = user.company
        exp = ""

        data = request.POST
        pk = data.get("pk")

        first_name = data.get("first_name")
        middle_name = data.get("middle_name")
        last_name = data.get("last_name")
        gender = data.get("gender")
        phone_1 = data.get("phone_1")
        phone_2 = data.get("phone_2")
        admin_access = True if data.get("admin_access") == "on" else False
        
        accessible_branches_list = data.getlist("accessible_branches")
        accessible_branches = company.branches.filter(pk__in=accessible_branches_list)

        user_roles_list = data.getlist("user_roles")
        user_roles = CGroup.objects.filter(pk__in=user_roles_list)

        email = data.get("email")
        username = data.get("username")

        with transaction.atomic():
            try: 
                if pk:
                    user = company.users.get(pk=pk)

                    user.email = email
                    if username:
                        user.username = username
                    user.save()

                    user.profile.first_name = first_name
                    user.profile.middle_name = middle_name
                    user.profile.last_name = last_name
                    user.profile.gender = gender
                    user.profile.phone_1 = phone_1
                    user.profile.phone_2 = phone_2
                    user.profile.admin_access = admin_access
                    user.profile.save()
                else:
                    # generate a random password
                    password = "password"
                    
                    user = company.users.create_user(
                        email=email,
                        password=password,
                        username=username,
                        company=company
                    )
                    UserProfile.objects.create(
                        user=user,
                        first_name=first_name,
                        middle_name=middle_name,
                        last_name=last_name,
                        gender=gender,
                        phone_1=phone_1,
                        phone_2=phone_2,
                        admin_access=admin_access
                    )
                
                user.accessible_branches.set(accessible_branches)
                user.c_groups.set(user_roles)
            except Exception as e:
                exp = str(e)
                print(exp)
        
        return self.get(request, error_message=str(exp), *args, **kwargs)


class ProductListView(LoginRequiredMixin, AdminAccessRequiredMixin, View):
    def get(self, request):
        user = request.user
        company = user.company

        products = company.products.all()
        branches = company.branches.all()

        for branch in branches:
            # get branch product ids
            ids = [b.product.id for b in branch.branch_products.all()]
            branch.product_ids = ids

        context = {
            "products": products,
            "company_branches": branches
        }
        
        return render(request, 'company/products.html', context)
    
    def post(self, request, *args, **kwargs):
        user = request.user
        company = user.company

        data = request.POST
        pk = data.get("pk")
        name = data.get("name")
        product_code = data.get("product_code")
        unit_price_str = data.get("unit_price")
        unit_price = int(unit_price_str.replace(",", ""))
        branch_ids = data.getlist("branch_ids")
        branches = company.branches.filter(pk__in=branch_ids)

        with transaction.atomic():
            if pk:
                product = company.products.get(pk=pk)
                product.name = name
                product.unit_price = unit_price
                product.product_code = product_code
                product.save()
            else:
                product = company.products.create(
                    company=company,
                    name=name,
                    product_code=product_code,
                    unit_price=unit_price
                )
            # update branch products
            for branch in branches:
                product.branch_products.get_or_create(
                    product=product,
                    branch=branch
                )
            # deactivate those not submited
            product.branch_products.exclude(branch__in=branches).update(is_active=False)

        return self.get(request, *args, **kwargs)

app/company/templates/company/branches.html
<c-layout>
    <header class="bg-base-100 rounded-box p-4">
        <h1 class="text-xl font-semibold mb-2">{{ company.name }}</h1>
        <div class="flex justify-between">
            <div class="text-sm">
                <p>{{ company.contact }}</p>
                <p>{{ company.address }}</p>
            </div>
            {% if ADMIN_MODE %}
            <div>
                <!-- Open the modal using ID.showModal() method -->
                <button class="btn" onclick="my_modal_2.showModal()">Create a new Branch</button>
                <dialog id="my_modal_2" class="modal">
                    <div class="modal-box">
                        <form action="{% url 'company:branches' %}?action=create_branch" method="post">
                            {% csrf_token %}
                            <fieldset class="fieldset">
                                <legend class="fieldset-legend">Name *</legend>
                                <input type="text" class="input w-full" name="branch_name" required />
                            </fieldset>
                            <fieldset class="fieldset">
                                <legend class="fieldset-legend">Email</legend>
                                <input type="email" class="input w-full" name="email" />
                            </fieldset>
                            <fieldset class="fieldset">
                                <legend class="fieldset-legend">Phone</legend>
                                <input type="tel" class="input w-full" name="phone_1" />
                            </fieldset>
                            <fieldset class="fieldset">
                                <legend class="fieldset-legend">Other Phone</legend>
                                <input type="tel" class="input w-full" name="phone_2" />
                            </fieldset>
                            <fieldset class="fieldset">
                                <legend class="fieldset-legend">Location</legend>
                                <input type="text" class="input w-full" name="location" />
                            </fieldset>
                            <div class="modal-action">
                                <!-- if there is a button in form, it will close the modal -->
                                <button class="btn btn-primary">Create</button>
                            </div>
                        </form>
                    </div>
                    <form method="dialog" class="modal-backdrop">
                        <button>close</button>
                    </form>
                </dialog>
            </div>
            {% endif %}
        </div>
    </header>
    
    <div class="grid gap-4 mt-4 md:grid-cols-2">
        {% for branch in branches %}
        <div class="card bg-base-100">
            <div class="card-body relative">
                <div class="card-title">{{ branch.name }}</div>
                <div>
                    {% if branch.email %}
                    <p>{{ branch.email }}</p>
                    {% endif %}
                    {% if branch.phone_1 %}
                    <p>{{ branch.phone_1 }}</p>
                    {% endif %}
                    {% if branch.phone_2 %}
                    <p>{{ branch.phone_2 }}</p>
                    {% endif %}
                    {% if branch.location %}
                    <p>{{ branch.location }}</p>
                    {% endif %}
                </div>

                <div class="flex gap-4">
                    {% if ADMIN_MODE %}
                    <button class="btn" onclick="branch_modal_{{ branch.pk }}_edit.showModal()">Edit</button>
                    {% endif %}
                    <a class="btn btn-neutral" href="{% url 'branches:landing' branch.id %}">View</a>
                </div>
                {% if ADMIN_MODE %}
                <dialog id="branch_modal_{{ branch.pk }}_edit" class="modal">
                    <div class="modal-box">
                        <form action="{% url 'company:landing' %}?action=edit_branch" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="pk" value="{{ branch.pk }}">
                            <fieldset class="fieldset">
                                <legend class="fieldset-legend">Name *</legend>
                                <input type="text" value="{% if branch.name %}{{ branch.name }}{% endif %}" class="input w-full" name="branch_name" required />
                            </fieldset>
                            <fieldset class="fieldset">
                                <legend class="fieldset-legend">Email</legend>
                                <input type="email" value="{% if branch.email %}{{ branch.email }}{% endif %}" class="input w-full" name="email" />
                            </fieldset>
                            <fieldset class="fieldset">
                                <legend class="fieldset-legend">Phone</legend>
                                <input type="tel" value="{% if branch.phone_1 %}{{ branch.phone_1 }}{% endif %}" class="input w-full" name="phone_1" />
                            </fieldset>
                            <fieldset class="fieldset">
                                <legend class="fieldset-legend">Other Phone</legend>
                                <input type="tel" value="{% if branch.phone_2 %}{{ branch.phone_2 }}{% endif %}" class="input w-full" name="phone_2" />
                            </fieldset>
                            <fieldset class="fieldset">
                                <legend class="fieldset-legend">Location</legend>
                                <input type="text" value="{% if branch.location %}{{ branch.location }}{% endif %}" class="input w-full" name="location" />
                            </fieldset>
                            <div class="modal-action">
                                <!-- if there is a button in form, it will close the modal -->
                                <button class="btn btn-primary">Update</button>
                            </div>
                        </form>
                    </div>
                    <form method="dialog" class="modal-backdrop">
                        <button>close</button>
                    </form>
                </dialog>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
</c-layout>

app/company/templates/company/landing.html
<c-base title="Select Branch">
    <div class="p-4">
        <header class="bg-base-100 rounded-box p-4">
            <h1 class="text-xl font-semibold mb-2">{{ company.name }}</h1>
            
            {% if branches %}
            <p>Select a Branch</p>
            {% endif %}
        </header>
        
        <div class="flex flex-col gap-4 mt-4 md:flex-row justify-around">
            {% for branch in branches %}
            <a href="{% url 'branches:landing' branch.id %}">
                <div class="card bg-base-200 outline outline-1 outline-base-300 hover:outline-primary transition-all">
                    <div class="card-body relative">
                        <div class="card-title link">{{ branch.name }}</div>
                    </div>
                </div>
            </a>
            {% empty %}
            <p>No branches available. Contact your administrator.</p>
            {% endfor %}
        </div>
    </div>
</c-base>