api/urls.py
from django.urls import path

app_name = "api"

urlpatterns = []

app/branches/urls.py
from django.urls import path
from . import views

app_name = "branches"

urlpatterns = [
    path("<int:bpk>", views.BranchesView.as_view(), name="landing"),
    path("<int:bpk>/products", views.ProductsView.as_view(), name="products"),
    path("<int:bpk>/products/<int:pk>", views.ProductDetailView.as_view(), name="product-detail"),
    path("<int:bpk>/sales", views.SalesView.as_view(), name="sales"),
    path("<int:bpk>/sales/form", views.SalesFormView.as_view(), name="sales_form"),
    path("<int:bpk>/sales/form/<int:pk>", views.SalesFormView.as_view(), name="sales_form_update"),
    path("<int:bpk>/sales/analytics", views.SalesAnalyticsView.as_view(), name="sales_analytics"),
]

dotsales/urls.py
from django.contrib import admin
from django.urls import path, include

from api.api import global_api

from .appsConfig import getAppUrls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", global_api.urls),

    path("unicorn/", include("django_unicorn.urls")),
]

urlpatterns += getAppUrls()

inventory/sales/urls.py
from django.urls import path

app_name = "sales"

urlpatterns = []

accounts/companies/models/Branch.py
from django.db import models
from django.utils.translation import gettext_lazy as _

class Branch(models.Model):
    company = models.ForeignKey("companies.Company", on_delete=models.CASCADE, related_name="branches")
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=200, blank=True, null=True)

    email = models.EmailField(blank=True, null=True)
    phone_1 = models.CharField(_("Phone 1"), max_length=15, blank=True, null=True)
    phone_2 = models.CharField(_("Phone 2"), max_length=15, blank=True, null=True)

    class Meta:
        unique_together = ("company", "name")

    def __str__(self):
        return f"{self.company.name} - {self.name}"
    
    def verify_product(self, product):
        return self.branch_products.filter(product=product).exists()

app/branches/models.py
from django.db import models

# Create your models here.

inventory/products/models/BranchProduct.py
from django.db import models

class BranchProduct(models.Model):
    branch = models.ForeignKey("companies.Branch", on_delete=models.CASCADE, related_name="branch_products")
    product = models.ForeignKey("products.Product", on_delete=models.CASCADE, related_name="branch_products")
    is_active = models.BooleanField(default=True)
    stock = models.DecimalField(max_digits=10, decimal_places=2, default=0)


    class Meta:
        unique_together = ("branch", "product")

    def __str__(self):
        return f"{self.product.name} at {self.branch.name}"
    
    def get_stock(self):
        # return stock omitting irrelevant decimal points ie .00
        return self.stock.normalize()
    
    def get_worth(self):
        return int(self.get_stock() * self.product.unit_price)

inventory/products/models/Product.py
from django.db import models

class Product(models.Model):
    company = models.ForeignKey("companies.Company", on_delete=models.CASCADE, related_name="products")
    name = models.CharField(max_length=100)
    product_code = models.CharField(max_length=50, null=True)
    unit_price = models.DecimalField(max_digits=10, decimal_places=0)

    class Meta:
        verbose_name_plural = "Products"
        # unique_together = ("company", "product_code")

    def __str__(self):
        return f"{self.name} ({self.product_code})"

inventory/sales/models/Sale.py
from django.db import models
from django.utils import timezone

class Sale(models.Model):
    STATUS_CHOICES = [
        ("PAID", "Paid"),
        ("PARTIALLY_PAID", "Partially Paid"),
        ("CREDIT", "Credit"),
    ]

    branch = models.ForeignKey("companies.Branch", on_delete=models.CASCADE, related_name="sales")

    date = models.DateField(default=timezone.now)

    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="CREDIT")
    due_date = models.DateField(blank=True, null=True)

    class Meta:
        ordering = ["-date"]
        verbose_name = "Sale"
        verbose_name_plural = "Sales"
        permissions = [
            ("analyze_profit", "Can analyze profit")
        ]

    def __str__(self):
        return f"Sale {self.id} - {self.branch.name} - {self.date}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    @property
    def total_amount(self):
        return sum(item.line_total() for item in self.items.all())

    @property
    def amount_paid(self):
        return sum(p.amount for p in self.payments.all())

    @property
    def balance(self):
        return self.total_amount - self.amount_paid
    
    @property
    def total_cost(self):
        return sum(item.get_cost() for item in self.items.all())
    
    @property
    def projected_profit(self):
        return sum(item.expected_profit() for item in self.items.all())
    
    @property
    def projected_income(self):
        return sum(item.expected_income() for item in self.items.all())
    
    current_income = lambda self: self.amount_paid
    current_profit = lambda self: self.amount_paid - self.total_cost

    def update_status(self):
        if self.balance <= 0:
            self.status = "PAID"
        elif self.amount_paid > 0:
            self.status = "PARTIALLY_PAID"
        else:
            self.status = "CREDIT"
        self.save()
    

inventory/sales/models/SaleItem.py
from django.db import models

class SaleItem(models.Model):
    sale = models.ForeignKey("sales.Sale", on_delete=models.CASCADE, related_name="items")
    product = models.ForeignKey("products.BranchProduct", on_delete=models.CASCADE, related_name="sales")
    stock_batch = models.ForeignKey("stock.StockBatch", on_delete=models.CASCADE, related_name="sales", null=True)
    quantity = models.DecimalField(max_digits=10, decimal_places=2)
    unit_price = models.DecimalField(max_digits=10, decimal_places=0, null=True, blank=True)
    discount = models.DecimalField(max_digits=10, decimal_places=0, null=True, blank=True)

    def line_total(self):
        return int(self.quantity * self.stock_batch.selling_price)
    
    def get_cost(self):
        return int(self.quantity * self.stock_batch.get_item_cost())
    
    def expected_income(self):
        return int(self.quantity * self.stock_batch.selling_price)
    
    def expected_profit(self):
        return self.expected_income() - self.get_cost()

app/branches/views.py
from datetime import datetime, date
import json
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views import View
from django.db import transaction


class BranchesView(LoginRequiredMixin, View):
    def get(self, request, bpk):
        user = request.user
        company = user.company
        branch = company.branches.get(pk=bpk)

        context = {
            'branch': branch,
        }
        
        return render(request, 'branches/branches.html', context)


class ProductsView(LoginRequiredMixin, View):
    def get(self, request, bpk):
        user = request.user
        company = user.company
        branch = company.branches.get(pk=bpk)

        products = branch.branch_products.all().prefetch_related('product')

        context = {
            'branch': branch,
            'products': products,
        }
        
        return render(request, 'branches/products.html', context)
    
class ProductDetailView(LoginRequiredMixin, View):
    def get(self, request, bpk, pk):
        user = request.user
        company = user.company
        branch = company.branches.get(pk=bpk)

        branch_product = branch.branch_products.get(pk=pk)

        stock_batches = branch_product.batches.filter(active=True).all().order_by('-date')
        stock_batches_count = stock_batches.count()

        total_balance = 0
        balance_worth = 0
        all_prices = []
        for batch in stock_batches:
            total_balance += batch.get_balance()
            balance_worth += batch.get_worth()
            all_prices.append(batch.selling_price)

        average_price = sum(all_prices) / len(all_prices) if all_prices else 0

        context = {
            'branch': branch,
            'branch_product': branch_product,
            'product': branch_product.product,

            'stock_batches_count': stock_batches_count,
            'stock_batches': stock_batches,

            'total_balance': total_balance,
            'balance_worth': balance_worth,
            'average_price': average_price
        }

        return render(request, 'branches/product_detail.html', context)
    
    def post(self, request, bpk, pk):
        user = request.user
        company = user.company
        branch = company.branches.get(pk=bpk)

        branch_product = branch.branch_products.get(pk=pk)

        action = request.POST.get("action")
        if action == "restock":
            return self.restock(request, bpk, pk, branch_product, branch)
        elif action == "update_stock":
            return self.update_stock(request, bpk, pk, branch_product)
        
        return self.get(request, bpk, pk)
    
    def restock(self, request, bpk, pk, branch_product, branch):
        data = request.POST

        date_str = data.get("date")
        date = datetime.strptime(date_str, "%Y-%m-%d").date()
        quantity_str = data.get("quantity")
        quantity = float(quantity_str.replace(",", ""))
        cost_str = data.get("cost")
        cost = float(cost_str.replace(",", ""))
        selling_price_str = data.get("selling_price")
        selling_price = float(selling_price_str.replace(",", ""))

        branch_product.batches.create(
            date=date,
            quantity=quantity,
            cost=cost,
            selling_price=selling_price,
            branch=branch,
            product=branch_product
        )

        return self.get(request, bpk, pk)
    
    def update_stock(self, request, bpk, pk, branch_product):
        data = request.POST

        pk = data.get("pk")
        date_str = data.get("date")
        date = datetime.strptime(date_str, "%Y-%m-%d").date()
        quantity_str = data.get("quantity")
        quantity = float(quantity_str.replace(",", ""))
        cost_str = data.get("cost")
        cost = float(cost_str.replace(",", ""))
        selling_price_str = data.get("selling_price")
        selling_price = float(selling_price_str.replace(",", ""))

        batch = get_object_or_404(branch_product.batches, pk=pk) # branch_product.batches.get(pk=pk)
        batch.date = date
        batch.quantity = quantity
        batch.cost = cost
        batch.selling_price = selling_price
        batch.save()

        return self.get(request, bpk, pk)


class SalesView(LoginRequiredMixin, View):
    def get(self, request, bpk, *args, **kwargs):
        data = request.GET
        if data.get("fetch_form"):
            return self.generate_sale_form(request, bpk, *args, **kwargs)

        user = request.user
        company = user.company
        branch = company.branches.get(pk=bpk)

        today = date.today()

        all_sales = branch.sales.all().order_by('-date')

        current_month_sales = all_sales.filter(date__year=today.year, date__month=today.month).all().order_by('-date')
        month_total = sum(sale.amount_paid for sale in current_month_sales)
        month_debt = sum(sale.balance for sale in current_month_sales)

        current_week_sales = all_sales.filter(date__year=today.year, date__week=today.isocalendar()[1]).all().order_by('-date')
        week_total = sum(sale.amount_paid for sale in current_week_sales)
        week_debt = sum(sale.balance for sale in current_week_sales)

        current_day_sales = all_sales.filter(date__year=today.year, date__month=today.month, date__day=today.day).all().order_by('-date')
        day_total = sum(sale.amount_paid for sale in current_day_sales)
        day_debt = sum(sale.balance for sale in current_day_sales)

        sales = branch.sales.filter(date__year=today.year, date__month=today.month, date__day=today.day).all().order_by('-date')
        total_amount = sum(sale.amount_paid for sale in sales)

        context = {
            'branch': branch,
            'sales': all_sales,
            'current_month_sales': current_month_sales,
            'month_total': month_total,
            'month_debt': month_debt,
            'current_week_sales': current_week_sales,
            'week_total': week_total,
            'week_debt': week_debt,
            'current_day_sales': current_day_sales,
            'day_total': day_total,
            'day_debt': day_debt,
            'today': today,
        }
        
        return render(request, 'branches/sales.html', context)
    

class SalesFormView(LoginRequiredMixin, View):
    def get(self, request, bpk, *args, **kwargs):
        user = request.user
        company = user.company
        branch = company.branches.get(pk=bpk)

        products = branch.branch_products.all().prefetch_related('product')

        pk = kwargs.get("pk")
        if pk:
            sale_ = branch.sales.get(pk=pk)
            sale = {
                "id": sale_.id,
                "date": sale_.date.strftime('%Y-%m-%d'),
                "sale_items": [],
                "payments": [],
            }

            for sale_item in sale_.items.all():
                sale["sale_items"].append({
                    "id": sale_item.id,
                    "product_id": sale_item.product.id,
                    "batch_id": sale_item.stock_batch.id,
                    "quantity": float(sale_item.quantity),
                })

            for payment in sale_.payments.all():
                sale["payments"].append({
                    "id": payment.id,
                    "payment_amount": int(payment.amount),
                    "payment_method": payment.method,
                    "payment_date": payment.payment_date.strftime('%Y-%m-%d'),
                })
            sale = json.dumps(sale).replace('"', "'")
        else:
            sale = None

        products_data = []

        for product in products:
            pdt_data = {
                'id': product.id,
                'name': product.product.name,
                'batches': []
            }
            batches = product.batches.filter(active=True).all().order_by('-date')

            if not batches.count():
                continue
            
            for batch in batches:
                pdt_data['batches'].append({
                    'id': batch.id,
                    'date': batch.date.strftime('%Y-%m-%d'),
                    'stock': int(batch.get_available_stock()),
                    'selling_price': int(batch.get_selling_price())
                })
            
            products_data.append(pdt_data)
        
        products_data = json.dumps(products_data).replace('"', "'")


        context = {
            'sale': sale,
            'branch': branch,
            'products_data': products_data
        }
        
        return render(request, 'branches/sales_form.html', context)

    def post(self, request, bpk, *args, **kwargs):
        user = request.user
        company = user.company
        branch = company.branches.get(pk=bpk)

        data = request.POST

        sale_id = kwargs.get("pk", None)
        date_str = data.get("date")
        date = datetime.strptime(date_str, "%Y-%m-%d").date()

        item_ids = data.getlist("item_id")
        item_product_ids = data.getlist("item_product_id")
        item_batch_ids = data.getlist("item_batch_id")
        item_quantities = data.getlist("item_quantity")

        payment_ids = data.getlist("payment_id")
        payment_dates = data.getlist("payment_date")
        payment_amounts = data.getlist("payment_amount")
        payment_methods = data.getlist("payment_method")

        with transaction.atomic():
            # create or update sale
            if sale_id:
                sale = branch.sales.get(pk=sale_id)
                sale.date = date
                sale.save()
            else:
                sale = branch.sales.create(
                    date=date,
                    branch=branch
                )

            # create or update sale items

app/branches/templates/branches/branches.html
<c-layout2>
    <header class="bg-base-100 rounded-box p-4">
        <span class="badge badge-accent badge-xs uppercase">Branch</span>
        <h1 class="text-xl font-semibold mb-2">{{ branch.name }}</h1>
        <div class="flex justify-between">
            <div class="flex gap-4 flex-wrap">
                {% if branch.email %}
                <p class="badge badge-sm">{{ branch.email }}</p>
                {% endif %}
                {% if branch.phone_1 %}
                <p class="badge badge-sm">{{ branch.phone_1 }}</p>
                {% endif %}
                {% if branch.phone_2 %}
                <p class="badge badge-sm">{{ branch.phone_2 }}</p>
                {% endif %}
                {% if branch.location %}
                <p class="badge badge-sm">{{ branch.location }}</p>
                {% endif %}
            </div>
        </div>
    </header>
</c-layout2>

app/branches/templates/branches/products.html
<c-layout2>
	<div class="stats shadow bg-base-100 mb-4">
		<div class="stat">
			<div class="stat-title">Total Products</div>
			<div class="stat-value text-primary">{{ products.count }}</div>
			{% comment %} <div class="stat-desc">21% more than last month</div> {% endcomment %}
		</div>
	</div>

	<div class="overflow-x-auto rounded-box bg-base-100">
		<table class="table">
			<thead>
				<tr>
					<th>Product</th>
					<th class="text-right">Unit Price</th>
					<th class="text-center">Stock Qty</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				{% for p in products %}
				<tr>
					<td>
						<div class="flex items-center gap-3">
							{% comment %}
							<div class="avatar">
								<div class="mask mask-squircle h-12 w-12">
									<img
										src="https://img.daisyui.com/images/profile/demo/2@94.webp"
										alt="Avatar Tailwind CSS Component" />
								</div>
							</div>
							{% endcomment %}
							<div>
								<div class="font-bold">{{ p.product.name }}</div>
								{% if p.product.product_code %}
								<div class="text-sm opacity-50">{{ p.product.product_code }}</div>
								{% endif %}
							</div>
						</div>
					</td>
					<td class="text-right">{{ p.product.unit_price }}</td>
					<td class="text-center">{{ p.get_stock }}</td>
					<td class="flex justify-end">
						<a
							href="{% url 'branches:product-detail' branch.pk p.pk %}"
							class="btn btn-neutral btn-xs"
							>View</a
						>
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</c-layout2>

app/branches/templates/branches/sales.html
{% load mytags %}

<c-layout2>
	<div class="stats stats-vertical md:stats-horizontal w-full shadow bg-base-100 mb-4">
		<div class="stat">
			<div class="stat-title">Sales Today</div>
			<div class="stat-value text-primary">{{ sales.count }}</div>
			{% comment %} <div class="stat-desc">21% more than last month</div> {% endcomment %}
		</div>
        <div class="stat">
			<div class="stat-title uppercase font-semibold">Cash In TODAY</div>
			<div class="stat-value text-secondary">{{ day_total|add_commas }}</div>
			<div class="stat-desc font-semibold text-error">- {{ day_debt|add_commas }} balances</div>
			<div class="stat-figure">
				
			</div>
		</div>
        <div class="stat">
			<div class="stat-title uppercase font-semibold">This week Cash In</div>
			<div class="stat-value text-neutral">{{ week_total|add_commas }}</div>
			<div class="stat-desc font-semibold text-error">- {{ week_debt|add_commas }} balances</div>
			<div class="stat-figure">
				<span class="text-2xl font-bold">/=</span>
			</div>
		</div>
        <div class="stat">
			<div class="stat-title uppercase font-semibold">This month Cash In</div>
			<div class="stat-value text-neutral">{{ month_total|add_commas }}</div>
			<div class="stat-desc font-semibold text-error">- {{ month_debt|add_commas }} balances</div>
			<div class="stat-figure">
				<span class="text-2xl font-bold">/=</span>
			</div>
		</div>
	</div>
    
    {% if request.user|has_perm:"sales.add_sale" %}
    <div class="action-bar p-0 overflow-hidden outline rounded-full mb-4 flex justify-between">
        <div></div>
        <div>
            <a class="btn btn-neutral" title="Create a sale" href="{% url 'branches:sales_form' branch.pk %}">
                <span>Create a sale</span>
                <i class='bx  bx-arrow-right-stroke'  ></i> 
            </a>
        </div>
    </div>
    {% endif %}

    <div x-data="{
        items_table: true
    }">
        <div role="tablist" class="tabs">
            <a role="tab" class="tab" :class="items_table ? 'tab-active' : ''" @click="items_table = true">Items</a>
            <a role="tab" class="tab" :class="!items_table ? 'tab-active' : ''" @click="items_table = false">Sales</a>
        </div>
        <div class="overflow-x-auto rounded-box bg-base-100">
            <table class="table" x-cloak x-show="items_table">
                <thead>
                    <tr>
                        <th>Item</th>
                        <th class="text-right">Amount</th>
                        {% if request.user|has_perm:"sales.analyze_profit" %}
                        <th class="text-right md:hidden">Profit</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for sale in sales %}
                    {% for item in sale.items.all %}
                    <tr>
                        <td>
                            <div class="flex items-center gap-3">
                                <div>
                                    <div class="font-bold">{{ item.product.product.name }}</div>
                                    {% if item.product.product.product_code %}
                                    <div class="text-sm opacity-50">{{ item.product.product.product_code }}</div>
                                    {% endif %}
                                </div>
                            </div>
                        </td>
                        <td class="text-right hidden md:table-cell">{{ item.expected_income|add_commas }}</td>
                        {% if request.user|has_perm:"sales.analyze_profit" %}
                        <td class="text-right hidden md:table-cell">{{ item.expected_profit|add_commas }}</td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                    {% endfor %}
                </tbody>
            </table>
            <table class="table" x-cloak x-show="!items_table">
                <thead>
                    <tr>
                        <th>Sale</th>
                        <th class="text-center hidden md:table-cell">Status</th>
                        <th class="text-right hidden md:table-cell">Amount Paid</th>
                        <th class="text-right hidden md:table-cell">Balance</th>
                        <th class="text-right md:hidden">Amounts</th>
                        {% if request.user|has_perm:"sales.change_sale" %}
                        <th></th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for sale in sales %}
                    <tr>
                        <td>
                            <div class="flex items-center gap-3">
                                <div>
                                    <div class="font-bold">{{ sale.date }}</div>
                                    {% if p.product.product_code %}
                                    <div class="text-sm opacity-50">{{ p.product.product_code }}</div>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="md:hidden">
                                <span 
                                    class="badge 
                                    badge-sm 
                                    uppercase
                                    {% if sale.status == "PAID" %}
                                    badge-success 
                                    {% elif sale.status == "PARTIALLY_PAID" %}
                                    badge-warning
                                    {% elif sale.status == "CREDIT" %}
                                    badge-alert
                                    {% endif %}
                                    "
                                >{{ sale.status }}</span>
                            </div>
                        </td>
                        <td class="text-center hidden md:table-cell">
                            <span 
                                class="badge 
                                badge-sm 
                                uppercase
                                {% if sale.status == "PAID" %}
                                badge-success 
                                {% elif sale.status == "PARTIALLY_PAID" %}
                                badge-warning
                                {% elif sale.status == "CREDIT" %}
                                badge-alert
                                {% endif %}
                                "
                            >{{ sale.status }}</span>
                        </td>
                        <td class="text-right hidden md:table-cell">{{ sale.amount_paid|add_commas }}</td>
                        <td class="text-right hidden md:table-cell">{{ sale.balance|add_commas }}</td>
                        <td class="text-right md:hidden font-semibold">
                            <div class="text-success">{{ sale.amount_paid|add_commas }}</div>
                            <div class="text-error">{{ sale.balance|add_commas }}</div>
                        </td>
                        {% if request.user|has_perm:"sales.change_sale" %}
                        <td class="flex justify-end">
                            <a
                                href="{% url 'branches:sales_form_update' branch.pk sale.pk %}"
                                class="btn btn-ghost btn-sm text-lg"
                                >
                                <i class='bx  bx-edit'  ></i> 
                                </a
                            >
                        </td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</c-layout2>

app/branches/templates/branches/sales_analytics.html
{% load mytags %}

<c-layout2>
	<main class="min-h-screen">

		<div class="">
			<div class="flex flex-col md:flex-row md:items-center md:justify-between mb-6">
				<h1 class="text-2xl font-bold text-gray-800 mb-2 md:mb-0">
					{{ branch.name }} Sales Analytics
				</h1>
			</div>

			<!-- Date Filter Form -->
			<div class="bg-white rounded-lg p-6 mb-6">
				<form
					method="get"
					class="flex flex-col sm:flex-row items-center space-y-4 sm:space-y-0 sm:space-x-4">
                    <label for="start_date" class="input">
                        <span class="font-semibold">From</span>
                        <input name="start_date" id="start_date" type="date" value="{{ start_date }}" class="grow">
                    </label>
                    <label for="end_date" class="input">
                        <span class="font-semibold">To</span>
                        <input name="end_date" id="end_date" type="date" value="{{ end_date }}" class="grow">
                    </label>
					<button type="submit" class="btn btn-primary w-full sm:w-auto">Filter</button>
				</form>
			</div>

            <div class="stats w-full stats-vertical sm:stats-horizontal bg-base-100 outline outline-1 outline-base-300 rounded-lg mb-4">
                {% comment %} Income {% endcomment %}
                <div class="stat">
                    <div class="stat-title">Income</div>
                    <div class="stat-value">{{ total_income|add_commas }}</div>
                    <div class="stat-desc text-secondary items-center flex gap-2" title="Projected Income">
                        <i class="bx bx-trending-up bx-sm"></i>
                        {{ projected_income|add_commas }}</div>
                </div>
                {% comment %} profit {% endcomment %}
                <div class="stat">
                    <div class="stat-title">Profit</div>
                    <div class="stat-value">{{ total_profit|add_commas }}</div>
                    <div class="stat-desc text-secondary items-center flex gap-2" title="Projected Income">
                        <i class="bx bx-trending-up bx-sm"></i>
                        {{ projected_profit|add_commas }}</div>
                </div>
                {% comment %} sales {% endcomment %}
                <div class="stat">
                    <div class="stat-title">Sales</div>
                    <div class="stat-value">{{ total_sales|add_commas }}</div>
                    <div class="stat-desc text-secondary items-center flex gap-2" title="Items sold">
                        <i class="bx bx-trending-up bx-sm"></i>
                        {{ total_items|add_commas }} Items
                    </div>
                </div>
                {% comment %} debt {% endcomment %}
                <div class="stat">
                    <div class="stat-title">Debt</div>
                    <div class="stat-value">{{ total_debt|add_commas }}</div>
                    <div class="stat-desc text-secondary items-center flex gap-2" title="Items sold">
                        {% comment %} <i class="bx bx-trending-up bx-sm"></i>
                        {{ total_items|add_commas }} Items {% endcomment %}
                    </div>
                </div>
            </div>

			<!-- Sales Table Section -->
			<div class="bg-white rounded-lg p-4">
				<h3 class="text-xl font-semibold text-gray-800 mb-4">Sales Details</h3>
				<div class="overflow-x-auto">
					<table class="table w-full">
						<thead>
							<tr>
								<th class="text-left text-sm font-medium text-gray-500">Date</th>
								<th class="text-right text-sm font-medium text-gray-500">Income</th>
								<th class="text-right text-sm font-medium text-gray-500">Debt</th>
								<th class="text-right text-sm font-medium text-gray-500">Cost</th>
								<th class="text-right text-sm font-medium text-gray-500">Profit</th>
							</tr>
						</thead>
						<tbody>
							{% for sale in sales %}
							<tr>
								<td class="whitespace-nowrap">{{ sale.date }}</td>
								<td class="whitespace-nowrap text-right">
									{{ sale.amount_paid|add_commas }}
								</td>
								<td class="whitespace-nowrap text-right">{{ sale.balance|add_commas }}</td>
								<td class="whitespace-nowrap text-right">
									{{ sale.total_cost|add_commas }}
								</td>
								<td class="whitespace-nowrap text-right">
									{{ sale.current_profit|add_commas }}
								</td>
							</tr>
							{% empty %}
							<tr>
								<td colspan="5" class="text-center py-4 text-gray-500">
									No sales found for this period.
								</td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</main>
</c-layout2>